name: Test PHPCS
on: [push, pull_request]
jobs: 
  demo: 
    name: demo Test PHPCS
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ls ${{github.workspace}}
      - name: Installer PHPCS
      run: composer global require "squizlabs/php_codesniffer=*"
    - name: tester PHPCS sur MesDates.php
      run: ~/.composer/vendor/bin/phpcs ./src
    - name: afficher date de demain
      run: php ./src/MesDates.php